# Generated by Django 3.1.7 on 2021-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoffers',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='planoffers',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planshistory',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='planshistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='PlanOffers',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='PlansHistory',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
