"""
Django settings for ThanksFinance project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loading env Values form .env file
env_file_path = os.path.join(BASE_DIR, "venv/.env")
load_dotenv(env_file_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_o=qfgo_l#0_gqb41xfzjk_9a46fww)23^!nma)21%zw2)()#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # Django Admin Theme
    'jazzmin',

    # System App
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Created Apps
    'users',
    'customers',
    'stripAPI',
    # Third party
    "rest_framework",
    "import_export",
    "oauth2_provider",
    "corsheaders",
    'django_extensions',
    'cities_light',

    # Documentation
    "rest_framework_docs",
    "drf_yasg",
    "multiselectfield",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",  # To keep the Browsable API
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

OAUTH2_PROVIDER = {
    "SCOPES": {

        "admin": "can access to administer portal and customer portal",
        "customer": "can access to customer portal only",
        # "supervisor": "can access to supervisor portal ony",

    },
    "ACCESS_TOKEN_EXPIRE_SECONDS": 36000,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 1209600,
}
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # To keep the Browsable API
    "oauth2_provider.backends.OAuth2Backend",
)

ROOT_URLCONF = 'ThanksFinance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ThanksFinance.wsgi.application'

# # Default user model
AUTH_USER_MODEL = "users.User"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'sqlite3',

        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'ThanksFinance_db',
        # 'USER': 'postgres',
        # 'PASSWORD': 'postgres',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Misc configs
URL_TYPE = "http://0.0.0.0:8000"

# Auth Keys
CLIENT_ID = "uufTU0fwxKWSxrgO4cDlzMTk0j5CR7hlHiocNJZy"
CLIENT_SECRET = "502V0Ouo3Mh5P729HCQOLVqOGqrZn5tQWztvqMvVUCYgHSOC1Fs1fuuFJmzq68kwoH6065X0eg9sDV1XClcgbDk0zsewax3SpmBw6nvFEJxmS2FtqqkuWxX5rmW1jbah"

# # Auth Keys
# CLIENT_ID = os.environ.get("CLIENT_ID")
# CLIENT_SECRET = os.environ.get("CLIENT_SECRET")

# Stripe Configs
STRIPE_KEY = os.environ.get("STRIPE_KEY")

# Rest framework doc
REST_FRAMEWORK_DOCS = {"HIDE_DOCS": True}
REST_FRAMEWORK_DOCS = {"HIDE_DOCS": os.environ.get("HIDE_DRFDOCS", False)}
REST_FRAMEWORK = {"DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema"}

# CORS configs
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key'
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "Thanks Finance",

    # Title on the brand, and the login screen (19 chars max)
    "site_header": "Thanks Finance",

    # square logo to use for your site, must be present in static files, used for favicon and brand on top left

    # "site_logo": 'stock.png',

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Thanks Finance",

    # Copyright on the footer
    "copyright": "Thanks Finance",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "users.User",

    # Field name on user model that contains avatar image
    "user_avatar": "user.profile_picture",

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},

        # # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [],

    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     # "books": [{
    #     #     "name": "Make Messages",
    #     #     "url": "make_messages",
    #     #     "icon": "fas fa-comments",
    #     #     "permissions": ["books.view_book"]
    #     # }]
    # },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free
    # for a list of icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "users.user": "fas fa-user",
        "users.plans": "fas fa-ruler-combined",
        "users.subscriptions": "far fa-clock",
        "users.transactions": "fas fa-funnel-dollar",
        "cities_light.city": "fas fa-city",
        "cities_light.country": "fas fa-globe-europe",
        "cities_light.region": "fas fa-map-marked-alt",
        "cities_light.subregion": "fas fa-map-signs",

        # "users.image": "fa fa-camera-retro",
        # "users.religion": "fas fa-globe",
        # "users.cast": "fas fa-adjust",
        # "users.userPermission": "fas fa-lock",

        # "partner.partner": "fas fa-user-plus",
        # "partner.channel": "fas fa-comments",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    # "show_ui_builder": False,
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    # "language_chooser": True,
    "language_chooser": False,

}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "codezilla.rakesh@gmail.com"
EMAIL_HOST_PASSWORD = "rakesh@321"
